//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C00_BanAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C00_BanAn()
        {
            this.C02_PhucVu = new HashSet<C02_PhucVu>();
        }
    
        public int Id { get; set; }
        public string TenBanAn { get; set; }
        public Nullable<int> SoBanAn { get; set; }
        public Nullable<int> SoGhe { get; set; }
        public Nullable<int> IdLoaiBan { get; set; }
        public Nullable<int> IdLoaiKhuVuc { get; set; }
        public Nullable<int> IdTrangThai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual C00_LoaiBan C00_LoaiBan { get; set; }
        public virtual C00_KhuVucAn C00_KhuVucAn { get; set; }
        public virtual Root_QuanLyTrangThai Root_QuanLyTrangThai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C02_PhucVu> C02_PhucVu { get; set; }
    }
}
