//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C01_SapXepMenu
    {
        public int Id { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public Nullable<int> IdMon { get; set; }
    
        public virtual C01_Menu C01_Menu { get; set; }
        public virtual C01_Mon C01_Mon { get; set; }
    }
}
