//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C01_CongThuc
    {
        public int Id { get; set; }
        public string GioiThieu { get; set; }
        public string ChiTietMon { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> SuaLanCuoi { get; set; }
        public Nullable<int> IdMon { get; set; }
    
        public virtual C01_Mon C01_Mon { get; set; }
    }
}
