//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C01_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C01_Menu()
        {
            this.C01_SapXepMenu = new HashSet<C01_SapXepMenu>();
        }
    
        public int Id { get; set; }
        public string TenMenu { get; set; }
        public Nullable<int> SoLuongMon { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> SuaLanCuoi { get; set; }
        public Nullable<int> IdLoaiThucDon { get; set; }
    
        public virtual C01_LoaiThucDon C01_LoaiThucDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C01_SapXepMenu> C01_SapXepMenu { get; set; }
    }
}
