//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C01_Mon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C01_Mon()
        {
            this.C01_CongThuc = new HashSet<C01_CongThuc>();
            this.C01_SapXepMenu = new HashSet<C01_SapXepMenu>();
            this.C01_SapXepNhom = new HashSet<C01_SapXepNhom>();
            this.C02_PhucVu = new HashSet<C02_PhucVu>();
            this.C03_CustomerReview = new HashSet<C03_CustomerReview>();
        }
    
        public int Id { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> IdTrangThai { get; set; }
        public string DonVi { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string GhiChu { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C01_CongThuc> C01_CongThuc { get; set; }
        public virtual Root_QuanLyTrangThai Root_QuanLyTrangThai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C01_SapXepMenu> C01_SapXepMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C01_SapXepNhom> C01_SapXepNhom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C02_PhucVu> C02_PhucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C03_CustomerReview> C03_CustomerReview { get; set; }
    }
}
