//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02_PhucVu
    {
        public int Id { get; set; }
        public Nullable<int> IdMon { get; set; }
        public Nullable<int> IdBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<bool> ThanhToan { get; set; }
        public string NgayTao { get; set; }
    
        public virtual C00_BanAn C00_BanAn { get; set; }
        public virtual C01_Mon C01_Mon { get; set; }
    }
}
