//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02_HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C02_HoaDon()
        {
            this.C02_ChiTietHoaDon = new HashSet<C02_ChiTietHoaDon>();
        }
    
        public int Id { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<int> IdLichSuBan { get; set; }
        public Nullable<decimal> PhaiThu { get; set; }
        public Nullable<decimal> ThucThu { get; set; }
        public Nullable<decimal> ChoNo { get; set; }
        public Nullable<decimal> TrietKhau { get; set; }
        public Nullable<int> MaVoucher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C02_ChiTietHoaDon> C02_ChiTietHoaDon { get; set; }
        public virtual C02_LichSuDungBanAn C02_LichSuDungBanAn { get; set; }
    }
}
