//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02_ChiTietHoaDon
    {
        public int Id { get; set; }
        public Nullable<int> IdHoaDon { get; set; }
        public Nullable<int> IdMonAn { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonVi { get; set; }
        public string GhiChu { get; set; }
    
        public virtual C02_HoaDon C02_HoaDon { get; set; }
    }
}
