//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhaHangEntities : DbContext
    {
        public QuanLyNhaHangEntities()
            : base("name=QuanLyNhaHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C00_BanAn> C00_BanAn { get; set; }
        public virtual DbSet<C00_KhuVucAn> C00_KhuVucAn { get; set; }
        public virtual DbSet<C00_LoaiBan> C00_LoaiBan { get; set; }
        public virtual DbSet<C00_NhaHang> C00_NhaHang { get; set; }
        public virtual DbSet<C01_CongThuc> C01_CongThuc { get; set; }
        public virtual DbSet<C01_LoaiThucDon> C01_LoaiThucDon { get; set; }
        public virtual DbSet<C01_Menu> C01_Menu { get; set; }
        public virtual DbSet<C01_Mon> C01_Mon { get; set; }
        public virtual DbSet<C01_NhomMon> C01_NhomMon { get; set; }
        public virtual DbSet<C01_SapXepMenu> C01_SapXepMenu { get; set; }
        public virtual DbSet<C01_SapXepNhom> C01_SapXepNhom { get; set; }
        public virtual DbSet<C02_ChiTietHoaDon> C02_ChiTietHoaDon { get; set; }
        public virtual DbSet<C02_HoaDon> C02_HoaDon { get; set; }
        public virtual DbSet<C02_PhucVu> C02_PhucVu { get; set; }
        public virtual DbSet<Root_DonVi> Root_DonVi { get; set; }
        public virtual DbSet<Root_NhomQuyen> Root_NhomQuyen { get; set; }
        public virtual DbSet<Root_NhomTrangThai> Root_NhomTrangThai { get; set; }
        public virtual DbSet<Root_QuanLyTrangThai> Root_QuanLyTrangThai { get; set; }
        public virtual DbSet<Root_Quyen> Root_Quyen { get; set; }
        public virtual DbSet<Root_TrangThai> Root_TrangThai { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
