//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResManager.DAO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Root_QuanLyTrangThai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Root_QuanLyTrangThai()
        {
            this.C00_BanAn = new HashSet<C00_BanAn>();
            this.C00_KhuVucAn = new HashSet<C00_KhuVucAn>();
            this.C00_LoaiBan = new HashSet<C00_LoaiBan>();
            this.C01_Mon = new HashSet<C01_Mon>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTrangThai { get; set; }
        public Nullable<int> IdNhomTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C00_BanAn> C00_BanAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C00_KhuVucAn> C00_KhuVucAn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C00_LoaiBan> C00_LoaiBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C01_Mon> C01_Mon { get; set; }
        public virtual Root_NhomTrangThai Root_NhomTrangThai { get; set; }
        public virtual Root_TrangThai Root_TrangThai { get; set; }
    }
}
